---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: alpine

inputs:
  - name: boot-twitter-sentiment

run:
  path: mvn
  args: ["package"]

params:
  TERM: -dumb
