endpoints:
  sensitive: true
  
management:
  cloudfoundry:
    skip-ssl-validation: true
  info:
    git:
      mode: full
      
logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG
        
server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: update

---

spring:
  profiles: dev    
  datasource:
    url: jdbc:mysql://localhost/twitter
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    
---

spring:
  profiles: cloud
